### ISSUE TITLE
打开一个新的章节, 运行到答题部分就进行不下去了

### ISSUE THREAD

**Issue by wangzilinn** [ZhangEliot/UlearningAutomatic#1]
在之前没有上过的专题中打开, 脚本可以开始可以正常运行,直到到第一个答题界面, 自动答题后所有答案均显示为undefined, 导致无法进行跳转.

**Comment by ZhangEliot** [comment]
你好，感谢你的反馈！目前得知优学院答案查询接口已更改，将会尽快更新脚本！

**Comment by ZhangEliot** [comment]
> 在之前没有上过的专题中打开, 脚本可以开始可以正常运行,直到到第一个答题界面, 自动答题后所有答案均显示为undefined, 导致无法进行跳转.

你好，感谢你的反馈！目前得知优学院答案查询接口已更改，将会尽快更新脚本！
